// app actionTypes::
export const GET_NODES_LIST = 'GET_NODES_LIST';
export const SET_NODES_LIST = 'SET_NODES_LIST';
export const SET_PAGE = 'SET_PAGE';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const TOGGLE_SPINNER = 'TOGGLE_SPINNER';
export const TOGGLE_SUCCESS_POPUP = 'TOGGLE_SUCCESS_POPUP';
export const SET_SOCKET_CLIENT = 'SET_SOCKET_CLIENT';
export const UPDATE_TOOLTIP_STATUS = 'UPDATE_TOOLTIP_STATUS';
export const TOGGLE_WARNING_POPUP = 'TOGGLE_WARNING_POPUP';



// account actionTypes::
export const GET_DISPUTES = 'GET_DISPUTES';
export const IS_WALLET = 'IS_WALLET';
export const GET_PAYMENT_REQUEST = 'GET_PAYMENT_REQUEST';
export const SET_PAYMENT_REQUEST = 'SET_PAYMENT_REQUEST';
export const SET_WALLET_ENCRYPTION_LIBRARY_AND_NOD_SELECTED = 'SET_WALLET_ENCRYPTION_LIBRARY_AND_NOD_SELECTED';
export const CONNECT = 'CONNECT';
export const RE_CONNECT = 'RE_CONNECT';
export const LOG_OUT = 'LOG_OUT';
export const SELECT_NODE = 'SELECT_NODE';
export const SET_TRUST_SCORE_AND_USERHASH = 'SET_TRUST_SCORE_AND_USERHASH';
export const GENERATE_ADDRESS = 'GENERATE_ADDRESS';
export const SET_ADDRESSES = 'SET_ADDRESSES';
export const SET_ADDRESS_WITH_BALANCE = 'SET_ADDRESS_WITH_BALANCE';
export const ADDRESS_SUBSCRIPTION = 'ADDRESS_SUBSCRIPTION';
export const OPEN_DISPUTE = 'OPEN_DISPUTE';
export const SAVE_DISPUTE_DETAILS = 'SAVE_DISPUTE_DETAILS';
export const REMOVE_DISPUTE_ITEM = 'REMOVE_DISPUTE_ITEM';
export const GET_FULLNODE_FEES = 'GET_FULLNODE_FEES';
export const SET_FEES = 'SET_FEES';
export const SEND_TX = 'SEND_TX';
export const UPDATE_BALANCE_OF_ADDRESS = 'UPDATE_BALANCE_OF_ADDRESS';
export const UPLAOD_EVIDENCE = 'UPLAOD_EVIDENCE';
export const UPDATE_EVIDENCE = 'UPDATE_EVIDENCE';
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const SEND_DISPUTE = 'SEND_DISPUTE';
export const SET_DISPUTES = 'SET_DISPUTES';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SET_WINDOW_WIDTH = 'SET_WINDOW_WIDTH';
export const SET_WIDTH = 'SET_WIDTH';
export const ON_SEND_MESSAGE = 'ON_SEND_MESSAGE';
export const GET_DISPUTE_DETAILS = 'GET_DISPUTE_DETAILS';
export const SET_DISPUTE_DETAILS = 'SET_DISPUTE_DETAILS';
export const DOWNLOAD_FILE = 'DOWNLOAD_FILE';
export const SET_IMAGE = 'SET_IMAGE';
export const UPDATE_COMMENT_IN_ITEMS = 'UPDATE_COMMENT_IN_ITEMS';
export const UPDATE_DOCUMENT_IN_ITEMS = 'UPDATE_DOCUMENT_IN_ITEMS';
export const UPDATE_ITEMS_STATUS = 'UPDATE_ITEMS_STATUS';
export const NOTIFICATION_CHANNEL = 'NOTIFICATION_CHANNEL';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';

